inference_gpu_ids = [0,1,2,3,4,5]
trainer_gpu_ids = [6,7]

max_steps = 200

[wandb]
project = "wordle"
name = "wordle"

[ckpt] # Checkpoint at the end of training

[model]
name = "PrimeIntellect/Qwen3-1.7B-Wordle-SFT"

[orchestrator]
seq_len = 8192
batch_size = 1024
rollouts_per_example = 16

[[orchestrator.env]]
id = "primeintellect/wordle"
name = "wordle"

[orchestrator.sampling]
max_tokens = 1024

[trainer] # Default trainer config

[inference.parallel]
dp = 3
tp = 2
