inference_gpu_ids = [0]
trainer_gpu_ids = [1]

max_steps = 100

[wandb]
project = "gsm8k-debug"
name = "gsm8k"

[model]
name = "PrimeIntellect/Qwen3-0.6B"

[orchestrator]
batch_size = 512
rollouts_per_example = 16
seq_len = 2048

[orchestrator.sampling]
max_tokens = 2048

[[orchestrator.env]]
id = "primeintellect/single-turn-math"
args = { dataset_name = "openai/gsm8k", dataset_subset = "main" }

[trainer] # Default trainer config

[inference] # Default inference config