max_steps = 6

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"
attn = "sdpa"

[optim]
lr = 5e-6

[grad_acc]
beta = 0.99
epsilon = 1e-12
acc_upload_interval = 1
upload_to_hf = true
hf_repo_id = "israel-adewuyi/Qwen2.5-0.5B-Instruct-accumulated_grad"
hf_private = false
