max_steps = 150

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"

[optim]
lr = 1e-4

[wandb]
platform = "tensorboard"
project = "slimpeft_v2"
name = "train_alphabetsort-qwen0.5B-sparsity-99_lr=1e4_random10"

