max_steps = 45

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"
attn = "sdpa" 

[optim]
lr = 1e-6

[wandb]
project = "primerl"
name = "train_test_run_2"

[load_mask]
repo_id = "israel-adewuyi/Qwen2.5-0.5B-Instruct-grad_masks"
beta = 0.99
step = 100
tolerance = 1e-06