max_steps = 300

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"
attn = "sdpa" 

[optim]
lr = 1e-4

[wandb]
project = "alphabetsort"
name = "train_hyperparamsweep_beta-0.99_tol-1e-7_step-5_batch-128_lr-1e-4"

[load_mask]
repo_id = "israel-adewuyi/Qwen2.5-0.5B-Instruct-grad_masks"
beta = 0.99
step = 5
tolerance = 1e-07