max_steps = 3

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"

[optim]
lr = 1e-6

[grad_acc]
beta = 0.99
epsilon = 1e-8
save_interval = 1
tolerance = 1e-5
save_masks = true
upload_to_hf = true
hf_repo_id = "test_masks"
hf_private = true
