max_steps = 100
batch_size = 512
seq_len = 8192
rollouts_per_example = 8
mask_truncated_completions = false
env = [
    { id = "hendrycks-math" },
]

[model]
name = "Qwen/Qwen2.5-1.5B"

[wandb]
platform = "tensorboard"
project = "slimpeft"
name = "orch_qwen1.5B-base-hendryksmath-sparsity=99.99-lr=4e03_154265random42"

[wandb.log_extras]
interval = 10

[sampling]
max_tokens = 2048

[eval]
env = [
    { id = "math500", num_examples = -1 },
    { id = "gsm8k", num_examples = -1 },
]
interval = 10
rollouts_per_example = 1

[eval.sampling]
max_tokens = 1024
temperature = 0.9
