max_steps = 100

[model]
name = "Qwen/Qwen2.5-1.5B"

[tokenizer]
chat_template = "{%- if messages[0]['role'] == 'system' %}\n    {{- '<|im_start|>system\n' + messages[0]['content'] + '<|im_end|>\n' }}\n{%- else %}\n    {{- '<|im_start|>system\nYou are a helpful mathematical AI assistant. Please reason step by step, and put your final answer within \\\\boxed{}.<|im_end|>\n' }}\n{%- endif %}\n{%- for message in messages %}\n    {%- if message['role'] == 'user' or (message['role'] == 'system' and not loop.first) %}\n        {{- '<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n' }}\n    {%- elif message['role'] == 'assistant' %}\n        {{- '<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>' + '\n' }}\n    {%- endif %}\n{%- endfor %}\n{%- if add_generation_prompt %}\n    {{- '<|im_start|>assistant\n' }}\n{%- endif %}\n"

[optim]
type = "sparse_adamw"
lr = 0.001

[wandb]
platform = "tensorboard"
project = "slimpeft"
name = "train_qwen1.5B-base-hendryksmath-sparsity=99.999-lr=1e03_15297random2001"

[load_mask]
repo_id = "israel-adewuyi/mask_qwen-1.5B"
num_active = "15297random2001"
