## to run on 2 H200
batch_size = 512
rollouts_per_example = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-14B"

[wandb]

[sampling]
max_tokens = 2048

[[env]]
id = "hendrycks-math"

[wandb.log_extras]
interval = 10

[eval]
interval = 50

[[eval.env]]
id = "math500"
rollouts_per_example = 1

[[eval.env]]
id = "aime2024"
rollouts_per_example = 16

[[eval.env]]
id = "aime2025"
rollouts_per_example = 16
