## to run on 8H200
batch_size = 512
rollouts_per_example = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "moonshotai/Moonlight-16B-A3B-Instruct"
trust_remote_code = true

[sampling]
max_tokens = 2048

[wandb]

[[env]]
id = "hendrycks-math"

[wandb.log_extras]
interval = 10

[eval]
interval = 50

[[eval.env]]
id = "math500"
rollouts_per_example = 1

[[eval.env]]
id = "aime2024"
rollouts_per_example = 16

[[eval.env]]
id = "aime2025"
rollouts_per_example = 16
