max_steps = 150
seq_len = 16384

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"

[orchestrator]
batch_size = 512
rollouts_per_example = 16

[orchestrator.sampling]
max_tokens = 512

[[orchestrator.env]]
id = "alphabet-sort"
args = { min_turns = 2, max_turns = 2 }

[trainer.wandb]
platform = "tensorboard"
project = "alphabet-sort-debug"
name = "trainer_alphabet-sort_4"

[orchestrator.wandb]
platform = "tensorboard"
project = "alphabet-sort-debug"
name = "orch_alphabet-sort_4"

[inference]


[trainer.grad_dump]
steps = [147, 148, 149]
output_dir = "grads"
