## to run on 8H100
batch_size = 512
rollouts_per_example = 16
seq_len = 2048
mask_truncated_completions = false

[model]
name = "Qwen/Qwen3-30B-A3B"

[[env]]
id = "hendrycks-math"

[sampling]
max_tokens = 2048

[wandb]

[[eval.env]]
id = "math500"
rollouts_per_example = 1

[[eval.env]]
id = "aime2024"
rollouts_per_example = 16

[[eval.env]]
id = "aime2025"
rollouts_per_example = 16

[wandb.log_extras]
interval = 10