max_steps = 20

[model]
name = "PrimeIntellect/Qwen3-0.6B-Reverse-Text-SFT"

[orchestrator]
batch_size = 128
rollouts_per_example = 16
seq_len = 2048

[orchestrator.sampling]
max_tokens = 128

[[orchestrator.env]]
id = "reverse-text"

[[orchestrator.env]]
id = "reverse-text"
name = "reverse-text-2"

[orchestrator.val]
interval = 1
num_examples = 16

[trainer.optim]
lr = 3e-6

[inference] # Default inference config