max_steps = 500
batch_size = 1024
seq_len = 8192
rollouts_per_example = 8

[sampling]
temperature = 0.6
max_tokens = 8192

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"

[wandb]

[[env]]
id = "acereason-math"

[wandb.log_extras]
interval = 50

[eval]
interval = 50

[[eval.env]]
id = "math500"
rollouts_per_example = 1

[[eval.env]]
id = "aime2024"
rollouts_per_example = 32

[[eval.env]]
id = "aime2025"
rollouts_per_example = 32

[ckpt]
interval = 100