max_steps = 1000
batch_size = 2048
seq_len = 8192
rollouts_per_example = 16
mask_truncated_completions = false

[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-1.5B"

[sampling]
max_tokens = 8192

[wandb]

[[env]]
id = "intellect-math"
args = { solve_rate_field = "solve_rate_qwen_r1_distill_7b", min_solve_rate = 0.4, max_solve_rate = 0.9 }

[wandb.log_extras]
interval = 50

[eval]
interval = 50

[[eval.env]]
id = "math500"
rollouts_per_example = 1

[[eval.env]]
id = "aime2024"
rollouts_per_example = 16

[[eval.env]]
id = "aime2025"
rollouts_per_example = 16

[ckpt]