trainer_gpu_ids = [0, 1]
inference_gpu_ids = [2, 3, 4, 5, 6, 7]
max_steps = 500

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"

[trainer.optim]
lr = 1e-6

[orchestrator]
batch_size = 512
rollouts_per_example = 16
seq_len = 2048

[orchestrator.sampling]
max_tokens = 2048

[[orchestrator.env]]
id = "hendrycks-math"

[orchestrator.buffer]
type = "difficulty-pool"
easy_fraction = 0.0
hard_fraction = 0.0
easy_border = 1.0
hard_border = 0.0

[orchestrator.val]
interval = 1
num_examples = 8
rollouts_per_example = 16

[orchestrator.eval]
interval = 10

[orchestrator.eval.sampling]
max_tokens = 2048

[[orchestrator.eval.env]]
id = "math500"
num_examples = 30
rollouts_per_example = 4

[[orchestrator.eval.env]]
id = "aime2024"
rollouts_per_example = 4

[[orchestrator.eval.env]]
id = "aime2025"
rollouts_per_example = 4

[inference.parallel]
tp = 2
dp = 3

