# Example of generating data in two single-turn environments (gsm8k and hendrycks)
num_examples = 16
rollouts_per_example = 4

[[env]]
id = "primeintellect/single-turn-math"
name = "gsm8k"
args = { dataset_name = "openai/gsm8k", dataset_subset = "main" }

[[env]]
id = "primeintellect/single-turn-math"
name = "hendrycks"
args = { dataset_name = "PrimeIntellect/Hendrycks-Math", dataset_subset = "default" }