# Example of generating data in a single single-turn environment (gsm8k)
num_examples = 16
rollouts_per_example = 4

[[env]]
id = "primeintellect/math-env"
args = { dataset_name = "openai/gsm8k", dataset_subset = "main" }
